### ISSUE TITLE
Fetching roles from policy should allow taking into account global permissions

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/metaproject#1]

**Comment by bdionne** [comment]
I switched back to using to using this repo and moved the operations I need into `EditTab`. I'm still seeing the null pointer exceptions when the root user is trying to open a project. I have a [commit](https://github.com/bdionne/metaproject/commit/b0373509e3c7a8ebb0654f5c8ed62d9a370e85b3) that fixes it for me. 

Some of the newer commits seemed to have addressed this but the problem still persists

**Comment by rsgoncalves** [comment]
Could you post the stack trace or steps to reproduce the exception?

Looking at the fix it won't work, because defaulting to returning all projects will make certain UIs show more than they should. The API method will have to change to include a Boolean or enum value, as well as downstream bundles. I had a fix in the pipeline from back when we discussed this, I'll unstash it and push it through.

**Comment by bdionne** [comment]
yes, I noticed that what seems to create dups. Here's the  [exception](https://gist.github.com/bdionne/4585350ba2c1d5b43e1b9f1a42060f6e) It comes from a ProjectNotInPolicy exception dues to the failure to take into account "all-projects"

**Comment by bdionne** [comment]
To reproduce, using [this config](https://gist.github.com/bdionne/6c7f563b8f3e847f2c0772d90f8bd533) login as root and open the `test-log-diff` project and then ask for all the active operations.
