### ISSUE TITLE
File path names in project are based on the OS that the config file is edited on

### ISSUE THREAD

**Issue by bdionne** [protegeproject/metaproject#4]
If a project is created on a windows box, a server running on Linux will be unable to load the history file.

Not sure what the ideal solution is here, perhaps when the `JSON` is deserialized the path names can be translated to match the `OS`

**Comment by rsgoncalves** [comment]
How can I replicate this? Do you get some JSON parsing exception? When parsing a JSON config, the project paths are used to create Java `File` instances -- is that what's failing?

In principle this should not be a problem on the API side. In a Protege client an admin creates a project with a local File, which gets flushed to the server. The added `Project` instance will (or should!) have a path with the server OS format.

**Comment by bdionne** [comment]
I'll let @NCIEVS describe the steps. I suspect the project was created using windows and so the file name had backslashes in it. Gilberto mentioned that changing them in the config file fixed it

**Comment by bdionne** [comment]
ok, I checked with GIlberto. He created the project on windows and uploaded the file to the server, which was on Linux. He wasn't able to open it. He then fixed the backslashes in the file field of the server config and restarted the server.

**Comment by rsgoncalves** [comment]
I think this has to do with how and where (client vs server) project instances are created and added to the config. @johardi have a look?

**Comment by johardi** [comment]
The bug should be fixed via https://github.com/protegeproject/protege-server/issues/31 but it is unconfirmed yet
